apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  image: {{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}

  {{- with .Values.sso }}
  {{- if .enabled }}
  config:
    xpack.security.authc.providers:
      oidc.oidc1:
        enabled: true
        order: 0
        realm: {{ .oidc.realm }}
      {{- if $.Values.kibanaBasicAuth.enabled }}
      basic.basic1:
        enabled: true
        order: 1
      {{- end }}
  {{- end }}
  {{- end }}

  elasticsearchRef:
    name: {{ .Release.Name }}

  {{- if .Values.istio.enabled }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  {{- end }}

  podTemplate:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: {{ .Values.kibana.serviceAccountName }}
      {{- if .Values.kibana.securityContext }}
      securityContext:
      {{- toYaml .Values.kibana.securityContext | nindent 8 }}
      {{- end }}
      updateStrategy:
        type: {{ .rollingUpdate }}
        rollingUpdate:
          maxUnavailable: {{ .maxUnavailable }}
      containers:
        - name: kibana
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
          lifecycle:
            {{- toYaml .Values.kibana.lifecycle | nindent 12 }}
          {{- if .Values.kibana.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.kibana.volumeMounts | nindent 10 }}
          {{- end }}
      {{- if .Values.kibana.volumes }}
      volumes:
      {{- toYaml .Values.kibana.volumes | nindent 6 }}
      {{- end }}
      {{- with .Values.kibana.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.istio.enabled }}
      automountServiceAccountToken: true
      {{- end }}
      {{- with .Values.kibana }}
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      {{- end }}
      {{- end }}
