{{- if and .Values.istio.enabled .Values.istio.elasticsearch.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-es-http
  trafficPolicy:
    tls:
      mode: SIMPLE
{{- end }}