{{- if .Values.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sso-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sso-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: elasticsearch-kibana
    app.kubernetes.io/component: sso
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  #xpack.security.authc.realms.oidc.{{ .Values.sso.oidc.realm }}.rp.client_secret: {{ .Values.sso.client_secret | default "" | b64enc }}
  xpack.security.authc.realms.oidc.{{ .Values.sso.oidc.realm }}.rp.client_secret: {{ .Values.sso.client_secret | default "" | b64enc }}
{{- end }}
